### PR TITLE
Updating vendor against e3de62298a730415c5d2ab72607ef6adadd6304d

### PR DESCRIPTION
**Pull request by AxiomSamarth**
**What this PR does / why we need it**:
This PR rebases CA with upstream CA corresponding to K8s v1.20.0

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```action developer

```

### CODE REVIEW

**Comment by AxiomSamarth** [comment]
@prashanth26 I would need some help here. I am not sure 
- Why a rebase upon master is being expected as I have already done it?
- I have resolved all the conflicts locally while doing this exercise. 
- Strange path error in the CI as well. 

Note - Before rebasing with the master, I had reset the master to commit hash [57cf6d00ef8af2760f3d94dc789002ef92eb4689](https://github.com/kubernetes/autoscaler/commit/57cf6d00ef8af2760f3d94dc789002ef92eb4689) which happens to be the release commit for CA with K8s v1.20.0.

**Comment by AxiomSamarth** [comment]
> /lgtm hope you have tested the CA locally again.

Of course. I did push the changes after testing.

**Review by prashanth26 — APPROVED** [review]
- I hope the vendor has been updated to MCM latest release unable to view changes properly due to large changes. 
- Have we updated the docs for revendor with `master merge`?
- How did you fix the Docker error?

**Comment by AxiomSamarth** [comment]
@prashanth26 

> I hope the vendor has been updated to MCM latest release unable to view changes properly due to large changes.

Yes, the MCM v0.41.0 which is the latest has been vendored.

> Have we updated the docs for revendor with master merge?

I thought I will update the FAQ along with my scale from zero changes (which will be the next PR)

> How did you fix the Docker error?

By changing the name of `Dockerfile.amd64` to 'Dockerfile`

**Comment by AxiomSamarth** [comment]
Merging this one as I need these changes to be present on master for the generic scale from zero PR to be raised.

@prashanth26 I hope there are no further comments.

**Pull request merged**
