### PR TITLE
Integration test

### LINKED ISSUE #110: Integration test for Gardener Autoscaler
**What would you like to be added**:
An integration test suite for Gardener Cluster Autoscaler that could be run both locally as well in the build pipeline with ease.

**Why is this needed**:
This is need to test the CA behaviour against an actual Shoot and to report any anomalies as such. Also, such an integration test suite would help in validating any adoptions/upgrades from upstream CA.

### PR DESCRIPTION
**Pull request by AxiomSamarth**
**What this PR does / why we need it**:
This PR introduces integration test suite for Gardener cluster autoscaler

**Which issue(s) this PR fixes**:
Partly Fixes #110 

**Special notes for your reviewer**:

**Release note**:

```improvement developer
Gardener CA now supports basic IT to run locally.
```

### CODE REVIEW

**Comment by himanshu-kun** [comment]
@AxiomSamarth just wanted to know why is the `updating vendor against ..` commit is required?

**Comment by AxiomSamarth** [comment]
> @AxiomSamarth just wanted to know why is the `updating vendor against ..` commit is required?

If I remember correctly, then I added the ginkgo modules in the `go.mod` file and ran that vendor script to vendor the Gingko modules. And as we know, the script adds this commit.

**Comment by himanshu-kun** [comment]
Okay, yes its added by script. I think a better option would be to add this dependency overrides in `go.mod-extra` file. I'll do so , could you give me push access to this branch?

**Comment by AxiomSamarth** [comment]
> Okay, yes its added by script. I think a better option would be to add this dependency overrides in `go.mod-extra` file. I'll do so , could you give me push access to this branch?

Indeed, ideally `go-mod-extra` is the right place to add any additional dependencies as the `go.mod` is overwritten on every execution of the `vendor-udpdate.sh`. But, there should be some reason why I added it there. I am not able to recall. 

Umm, do we have the `go.mod-extra` file in the latest version of upstream CA?

PS - I will provide the access to this branch.

**Comment by himanshu-kun** [comment]
> Umm, do we have the go.mod-extra file in the latest version of upstream CA?

no we don't. I think that's why you added it there. I'll see if there comes any difference by updating in `go.mod-extra`. If not I'll merge this one only.
Thanks for providing the access.

**Pull request merged**
