### PR TITLE
Set GOOS,GOARCH env and ldflags option in .ci/build file

### PR DESCRIPTION
**Pull request by himanshu-kun**
**What this PR does / why we need it**:
Bring .ci/build in sync with Makefile way of creating binary. This is required after we started using `gcr.io/distroless/static:latest-amd64` image in `Dockerfile.amd64`

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
- done only for amd64 architecture
**Release note**:

```bugfix user
Bug stopping autoscaler to run because of architecture incompatibility is fixed
```

### CODE REVIEW

**Review by unmarshall — COMMENTED** [review]
If you wish to reduce the size further you can strip off DWARF generation which removes the possibility for you to connect a gbd (debugger) (option to use `-w`)

As discussed building for different architectures (ARM64 and AMD64) will be taken up later.

**Comment by himanshu-kun** [comment]
cc @ialidzhikov 
Would be making a patch release...
We missed it as we created the binary using `make build` and not `.ci/build` while testing.

**Review by unmarshall — APPROVED** [review]
/lgtm

**Comment by ialidzhikov** [comment]
> Would be making a patch release... We missed it as we created the binary using `make build` and not `.ci/build` while testing.

Feel free to close https://github.com/gardener/gardener/pull/6428 and open new PR with the new image.

**Pull request merged**
